### ISSUE TITLE
Release 5.6.2 Uses MSP-EXP432P401R Instead of MSP-EXP432P401RR

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp432r-core#13]
Release 5.6.2 uses `MSP-EXP432P401R` instead of `MSP-EXP432P401RR` for the MSP-EXP432P401R red, prompting confusion with the MSP-EXP432P401R black.

Release 5.6.1 was using `MSP-EXP432P401RR` for the MSP-EXP432P401R red.

**Comment by rei-vilo** [comment]
As a recommended solution, declare the MSP-EXP432P401R black board deprecated and remove the **Energia MSP432 boards by Energia version 3.8.0** from the boards manager.

**Comment by robertinant** [comment]
MSP430 black board has been removed.
