### ISSUE TITLE
Workshop — Blynk fails to send float numbers

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp432r-core#22]
Sending `float` numbers with [Blynk](https://www.blynk.cc) fails with the MSP432RED 5.23.1 package, but works with the MSP432 3.8.0 package.

```
    float p = random(220, 330) / 10.0;
    Blynk.virtualWrite(1, p); // °C
```

Might be related to #17.

**Comment by robertinant** [comment]
This is the cause of #17 which has been fixed and verified with Blynk also.
