### ISSUE TITLE
Windows 7 and 10 fails to resolve path to Java

### ISSUE THREAD

**Issue by StefanSch** [energia/msp432r-core#23]
During build the system claims that it can not find java with an error that
{runtime.ide.path}/java/bin/java
could not be found

changing this in platfrom.txt fixes the issue (locally)
#build.ino2cpp.cmd.windows={runtime.ide.path}/java/bin/java
build.ino2cpp.cmd.windows=c:/energia-1.6.10E18/java/bin/java

**Comment by StefanSch** [comment]
Just got this reported this issue from someone again.

**Comment by robertinant** [comment]
Fixed in > 5.25.x
