### ISSUE TITLE
Weird Access is denied issue on Upload

### ISSUE THREAD

**Issue by fcooper** [energia/msp432r-core#28]
OS: Windows 10 64bit
IDE Version: Energia 1.8.7E21
Board: MSP_EXP432E401Y
Core: MSP432 EMT Red v5.25.0

A student received the below error message when uploading code to their launchpad. I'm waiting for the verbose output but for now here is the error message that I received.

```
Sketch uses 40536 bytes (15%) of program storage space. Maximum is 262144 bytes.
Global variables use 8032 bytes (12%) of dynamic memory, leaving 57504 bytes for local variables. Maximum is 65536 bytes.
boost::filesystem::create_directories: Access is denied: "C:\Users\1#p\AppData\Local\Texas Instruments"
If this continues, please run fsclean or set TI_APPDATA_DIR to directory you have permissions to access
An error occurred while uploading the sketch
```

**Comment by robertinant** [comment]
Would be good to have the verbose output. It seems like this comes from DSLite. There is a # in the username which might be causing the issue.

**Comment by fcooper** [comment]
I did a quick test and having a # in the username didn't cause an issue. I'm going to close this since I asked the person for more details and found out it wasn't even the person reporting this issue computer. It was another persons computer and the class is now over. Likely won't get the data dump we need. I'll open this back up if this pops up again or if its possible to reproduce it.
