### ISSUE TITLE
Spi modes 0/1 and 2/3 definitions incorrect (5.25.0)

### ISSUE THREAD

**Issue by JRDavisUF** [energia/msp432r-core#34]
It looks like the definitions for SPI_MODE0 and 1 (and the definitions for SPI_MODE2 and 3) have been swapped when going from 5.23.1 to 5.25.0.  My perusal of the TI documentation seems to indicate that the 5.23.1 versions were correct.  
 
5.23.1\cores\msp432r\ti\runtime\wiring\SPI.h

#define SPI_MODE0 SPI_POL0_PHA0
#define SPI_MODE1 SPI_POL0_PHA1
#define SPI_MODE2 SPI_POL1_PHA0
#define SPI_MODE3 SPI_POL1_PHA1

5.25.0\cores\msp432r\ti\runtime\wiring\SPI.h

#define SPI_MODE0 SPI_POL0_PHA1
#define SPI_MODE1 SPI_POL0_PHA0
#define SPI_MODE2 SPI_POL1_PHA1
#define SPI_MODE3 SPI_POL1_PHA0

**Comment by robertinant** [comment]
Fixed in 5.25.1 and is available through the board manager.

**Comment by rei-vilo** [comment]
It looks like release 5.25.1 kept the wrong definitions.

https://github.com/energia/msp432r-core/blob/0faf18b698c69007ca1a132bd61c54a502158f3b/cores/msp432r/ti/runtime/wiring/SPI.h#L41-L44

**Comment by rei-vilo** [comment]
And PR #36.
