### ISSUE TITLE
LED1 not defined in pins_energia.h

### ISSUE THREAD

**Issue by vsupacha** [energia/msp432r-core#7]
LED1 is referred in MSP432R Launchpad pinout. But no LED1 is defined properly in the pins_energia.h file, so I got "LED1 was not declared". The version I used is 5.6.1.

**Comment by robertinant** [comment]
Thanks, that's a bug and I'll get it fixed. In the meantime you can use YELLOW_LED instead which addresses LED1.

**Comment by robertinant** [comment]
Fixed and will be in the next release.
